# AUTHOR: Jon Tanner Nelson
# LAST UPDATED: 10-8-2022
# CONTENTS: GWAS.asso.study.data, Populations
# PURPOSE: Data documentation


#' Populations of Genomic Data - Ensembl Aggregation
#'
#' Key population labels which map projects and their specific terms for populations to human readable population ancestries. Sample counts of various populations is also included.
#'
#' @format ## `Populations`
#' A data.table with 73 rows and 4 columns:
#' \describe{
#'  \item{Population_abbreviation}{The abbreviated terms which describe the project source of data as well as the population sampled in the project}
#'  \item{Sample_Count}{Number of individuals sampled}
#'  \item{Pop_Ancestry}{Ancestry of each population}
#'  \item{PopAnces_Graph_Labels}{Condensed versions of 'Pop_Ancestry' column, created for use as labels when graphing. The shortened names capture the most pertinent details of each ancestry while allowing for cleaner more uniform labeling in graphs.}
#' }
#'
#' @source <https://useast.ensembl.org/info/genome/variation/species/populations.html>
"Populations"

#' GWAS Catalog Associations and Studies Tables Merged
#'
#' After downloading studies and associations tables from GWAS catalog for several terms which fall under the umbrella 'air pollution' they were merged into a single table.
#' The data is all generated by researchers performing GWAS studies, and curated by the maintainers of the GWAS catalog.
#'
#' @format ## `GWAS.asso.study.data`
#' A data.table with 202 rows and 22 columns, the columns / variables come directly from GWAS catalog information concerning the meaning of each variable can be found at <https://www.ebi.ac.uk/gwas/docs/faq>. Additional searching within the GWAS catalog site may be necessary to verify exact meaning and purpose of values within this data set.
#'
#' @source <https://www.ebi.ac.uk/gwas/search?query=air%20pollution>
"GWAS.asso.study.data"
